---
name: Validation

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Run Validation Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run markdown linting
        run: npm run lint:md
        continue-on-error: false

      - name: Run spell checking
        run: npm run lint:spelling
        continue-on-error: false

      - name: Run formatting check
        run: npx prettier --check '**/*.{md,json,yml,yaml}'
        continue-on-error: false

      - name: Validate YAML front matter
        run: npm run validate:frontmatter
        continue-on-error: false

      - name: Check for broken links
        run: npm run validate:links
        continue-on-error: true

      - name: Generate documentation index
        run: npm run docs:index:output

      - name: Check if INDEX.md is up to date
        run: |
          if ! git diff --exit-code INDEX.md; then
            echo "ERROR: INDEX.md is out of date. Run 'npm run docs:index' locally and commit the changes."
            exit 1
          fi

      - name: Comment PR with validation results
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Validation checks failed. Please review the workflow logs and fix the issues before merging.'
            })

      - name: Comment PR with success
        if: github.event_name == 'pull_request' && success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All validation checks passed successfully!'
            })

